#!/system/bin/sh

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables

# Variables
RESTORE="0"
GPU_THROTTLING=
CPU_RATELIMITS=
IOWAIT_BOOST=
RAM_SWAP=
POWER_EFFICIENT=
GPU_POWER_LEVEL=
GPU_POWER_MANAGEMENT=
SULTAN_OPTIMIZATIONS=

# Avoid conflict & restore override
[ "$RESTORE" ] && if [ "$RESTORE" -eq 0 ]; then

[ "$GPU_THROTTLING" ] && if [ "$GPU_THROTTLING" -eq 1 ]; then
    echo "1" > $KGSL/throttling
elif [ "$GPU_THROTTLING" -eq 0 ]; then
    echo "0" > $KGSL/throttling
fi

[ "$CPU_RATELIMITS" ] && if [ "$CPU_RATELIMITS" -eq 1 ]; then
    if [ -d $S2 ]; then
        droid $S2/up_rate_limit_us "500"
        droid $S2/down_rate_limit_us "20000"
    elif [ -e $SC ]; then
        for cpu in /sys/devices/system/cpu/*/cpufreq/schedutil
        do
            droid "${cpu}/up_rate_limit_us" "500"
            droid "${cpu}/down_rate_limit_us" "20000"
        done
    fi
fi

[ "$IOWAIT_BOOST" ] && if [ "$IOWAIT_BOOST" -eq 1 ]; then
    if [ -d $S2 ]; then
        echo "1" > $S2/iowait_boost_enable
    elif [ -e $SC ]; then
        for cpu in /sys/devices/system/cpu/*/cpufreq/schedutil
        do
            echo "1" > "${cpu}/iowait_boost_enable"
        done
    fi
elif [ "$IOWAIT_BOOST" -eq 0 ]; then
    if [ -d $S2 ]; then
        echo "0" > $S2/iowait_boost_enable
    elif [ -e $SC ]; then
        for cpu in /sys/devices/system/cpu/*/cpufreq/schedutil
        do
            echo "0" > "${cpu}/iowait_boost_enable"
        done
    fi
fi

[ "$RAM_SWAP" ] && if [ "$RAM_SWAP" -eq 1 ]; then
    droid $SWP 60
fi

[ "$POWER_EFFICIENT" ] && if [ "$POWER_EFFICIENT" -eq 1 ]; then
    echo "1" > $PWR
elif [ "$POWER_EFFICIENT" -eq 0 ]; then
    echo "0" > $PWR
fi

[ "$GPU_POWER_LEVEL" ] && if [ "$GPU_POWER_LEVEL" -eq 1 ]; then
    echo "0" > $KGSL/default_pwrlevel
elif [ "$GPU_POWER_LEVEL" -eq 0 ]; then
    echo "$MIN_GPU_POWER_LEVEL" > $KGSL/default_pwrlevel
fi

[ "$GPU_POWER_MANAGEMENT" ] && if [ "$GPU_POWER_MANAGEMENT" -eq 1 ]; then
    echo "1" > $KGSL/force_bus_on
    echo "1" > $KGSL/force_clk_on
    echo "1" > $KGSL/force_no_nap
    echo "1" > $KGSL/force_rail_on
elif [ "$GPU_POWER_MANAGEMENT" -eq 0 ]; then
    echo "0" > $KGSL/force_bus_on
    echo "0" > $KGSL/force_clk_on
    echo "0" > $KGSL/force_no_nap
    echo "0" > $KGSL/force_rail_on
fi

[ "$SULTAN_OPTIMIZATIONS" ] && if [ "$SULTAN_OPTIMIZATIONS" -eq 1 ]; then
    echo "Y" > $LYB_TASK/parameters/lyb_sultan_pid
    echo "Y" > $LYB_TASK/parameters/lyb_sultan_pid_shrink
elif [ "$SULTAN_OPTIMIZATIONS" -eq 0 ]; then
    echo "N" > $LYB_TASK/parameters/lyb_sultan_pid
    echo "N" > $LYB_TASK/parameters/lyb_sultan_pid_shrink
fi

elif [ "$RESTORE" -eq 1 ]; then
restore
fi
