#!/system/bin/sh

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables
. /data/adb/modules/DroidConsole/system/bin/restore

# Variables
RESTORE=
GPU_THROTTLING=
CPU_RATELIMITS=
IOWAIT_BOOST=
RAM_SWAP=
POWER_EFFICIENT=
GPU_POWER_LEVEL=
GPU_POWER_MANAGEMENT=
SULTAN_OPTIMIZATIONS=

if [ "$RESTORE" -eq 1 ]; then
    echo "$BCK_RAM_SWAPPINESS" > $SWP
    echo "$BCK_GPU_THROTTLING" > $KGSL/throttling
    echo "$BCK_GPU_FORCE1" > $KGSL/force_bus_on
    echo "$BCK_GPU_FORCE2" > $KGSL/force_clk_on
    echo "$BCK_GPU_FORCE3" > $KGSL/force_no_nap
    echo "$BCK_GPU_FORCE4" > $KGSL/force_rail_on
    echo "$BCK_GPU_PWR" > $KGSL/default_pwrlevel
fi

if [ "$GPU_THROTTLING" -eq 1 ]; then
    echo "1" > $KGSL/throttling
elif [ "$GPU_THROTTLING" -eq 0 ]; then
    echo "0" > $KGSL/throttling
fi

if [ "$CPU_RATELIMITS" -eq 1 ]; then
    if [ -d $S2 ]; then
        echo "500" > $S2/up_rate_limit_us
        echo "20000" > $S2/down_rate_limit_us
    elif [ -e $SC ]; then
        for cpu in /sys/devices/system/cpu/*/cpufreq/schedutil
        do
            echo "500" > "${cpu}/up_rate_limit_us"
            echo "20000" > "${cpu}/down_rate_limit_us"
        done
    fi
fi

if [ "$IOWAIT_BOOST" -eq 1 ]; then
    if [ -d $S2 ]; then
        echo "1" > $S2/iowait_boost_enable
    elif [ -e $SC ]; then
        for cpu in /sys/devices/system/cpu/*/cpufreq/schedutil
        do
            echo "1" > "${cpu}/iowait_boost_enable"
        done
    fi
elif [ "$IOWAIT_BOOST" -eq 0 ]; then
    if [ -d $S2 ]; then
        echo "0" > $S2/iowait_boost_enable
    elif [ -e $SC ]; then
        for cpu in /sys/devices/system/cpu/*/cpufreq/schedutil
        do
            echo "0" > "${cpu}/iowait_boost_enable"
        done
    fi
fi

if [ "$RAM_SWAP" -eq 1 ]; then
    echo "60" > $SWP
fi

if [ "$POWER_EFFICIENT" -eq 1 ]; then
    echo "1" > $PWR
elif [ "$POWER_EFFICIENT" -eq 0 ]; then
    echo "0" > $PWR
fi

if [ "$GPU_POWER_LEVEL" -eq 1 ]; then
    echo "0" > $KGSL/default_pwrlevel
elif [ "$GPU_POWER_LEVEL" -eq 0]; then
    echo "$MIN_GPU_POWER_LEVEL" > $KGSL/default_pwrlevel
fi

if [ "$GPU_POWER_MANAGEMENT" -eq 1 ]; then
    echo "1" > $KGSL/force_bus_on
    echo "1" > $KGSL/force_clk_on
    echo "1" > $KGSL/force_no_nap
    echo "1" > $KGSL/force_rail_on
elif [ "$GPU_POWER_MANAGEMENT" -eq 0]; then
    echo "0" > $KGSL/force_bus_on
    echo "0" > $KGSL/force_clk_on
    echo "0" > $KGSL/force_no_nap
    echo "0" > $KGSL/force_rail_on
fi

if [ "$SULTAN_OPTIMIZATIONS" -eq 1 ]; then
    echo "Y" > $LYB_TASK/parameters/lyb_sultan_pid
    echo "Y" > $LYB_TASK/parameters/lyb_sultan_pid_shrink
elif [ "$SULTAN_OPTIMIZATIONS" -eq 0]; then
    echo "N" > $LYB_TASK/parameters/lyb_sultan_pid
    echo "N" > $LYB_TASK/parameters/lyb_sultan_pid_shrink
fi