#!/system/bin/sh
# Author: NotZeetaa

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables

main() {
    clear
    echo -en "\e[40m\e[37m"
    red
    animation_title
    echo "*****************************"
    animation_title
    echo "      × DroidConsole ×      "
    animation_title
    echo "*****************************"
    green
    space
    animation
    echo "1 - CPU tweaks"
    animation
    echo "2 - GPU tweaks"
    animation
    echo "3 - RAM tweaks"
    animation
    echo "4 - Latency tweaks"
    animation
    echo "5 - Miscellaneous"
    animation
    echo "6 - Restore"
    animation
    echo "7 - Github"
    animation
    echo "8 - About"
    animation
    echo "9 - Donate"
    animation
    echo "10 - Exit"
    space
    reset
    echo "Your input: "
    read input
    case $input in
        1)
            cpu
            ;;
        2)
            gpu
            ;;
        3)
            ram
            ;;
        4)
            latency
            ;;
        5)
            misc
            ;;
        6)
            clear
            red
            animation_title
            echo "*****************************"
            animation_title
            echo "      × Restore ×      "
            animation_title
            echo "*****************************"
            space
            red
            echo " This will restore all changes that DroidConsole made"
            space
            echo " Wanna restore all changes?"
            green
            space
            animation
            echo "1 - Yes"
            animation
            echo "2 - Main"
            animation
            echo "3 - Exit"
            space
            reset
            echo "Your input: "
            read input
            case $input in
                1)
                    resetprop -n droid.restore 1 && sed -i '/droid.restore=/s/.*/droid.restore=1/' $DPROP
                    finish
                    ;;
                2)
                    main
                    ;;
                3)
                    leave
                    ;;
                *)
                    red
                    echo "Invalid input!"
                    reset
                    ;;
            esac
            ;;
        7)
            clear
            blue
            animation
            echo "Our github link:"
            space
            animation
            echo "× https://github.com/NotZeetaa/DroidConsole ×"
            space
            animation
            echo "1 - Go back"
            animation
            echo "2 - Exit"
            reset
            space
            animation
            echo "Your input: "
            read input2
            if [ $input2 -eq "1" ]; then
                main
            elif [ $input2 -eq "2" ]; then
                leave
            fi
            reset
            ;;
        8)
            clear
            green
            echo "--------------------------------------------------------------"
            echo "              DroidConsole - Terminal Android Toolbox         "
            echo "--------------------------------------------------------------"
            echo ""
            echo "DroidConsole is a versatile toolbox designed for Android devices,"
            echo "empowering users with a powerful terminal interface for various tasks"
            echo "and commands. From system management to development utilities,"
            echo "DroidConsole provides a seamless experience for users accustomed"
            echo "to working within a command-line environment on their Android devices."
            echo ""
            echo "Project Name: DroidConsole"
            echo "Version: $VERSION"
            echo "License: MIT License"
            echo ""
            echo "--------------------------------------------------------------"
            echo "                              Author                          "
            echo "--------------------------------------------------------------"
            echo ""
            echo "DroidConsole is developed and maintained by NotZeetaa."
            echo "For any inquiries, feedback, or contributions, please contact NotZeetaa (Telegram & GitHub)."
            echo ""
            echo "--------------------------------------------------------------"
            echo "                           License Information               "
            echo "--------------------------------------------------------------"
            echo ""
            echo "DroidConsole is licensed under the MIT License."
            echo "For more information, please refer to the LICENSE file included with the distribution."
            echo ""
            echo "--------------------------------------------------------------"
            echo "                           Disclaimer                        "
            echo "--------------------------------------------------------------"
            echo ""
            echo "This software is provided as-is and without warranty. Use at your own risk."
            space
            animation
            echo "1 - Go back"
            animation
            echo "2 - Exit"
            reset
            space
            animation
            echo "Your input: "
            read input
            if [ $input -eq "1" ]; then
                main
            elif [ $input -eq "2" ]; then
                leave
            fi
            ;;
        9)
            am start -a android.intent.action.VIEW -d "http://notzeetaa.github.io/Donate-NotZeetaa"
            main
            ;;
        10)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

# Call the main function
main
