#!/system/bin/sh
# Author: NotZeetaa
# Version: BETA 2

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables

main() {
    clear
    echo -en "\e[40m\e[37m"
    red
    animation_title
    echo "*****************************"
    animation_title
    echo "      × DroidConsole ×      "
    animation_title
    echo "*****************************"
    green
    space
    animation
    echo "1 - CPU tweaks"
    animation
    echo "2 - GPU tweaks"
    animation
    echo "3 - RAM tweaks"
    animation
    echo "4 - Miscellaneous"
    animation
    echo "5 - Github"
    animation
    echo "6 - About"
    animation
    echo "7 - Donate"
    animation
    echo "8 - Exit"
    space
    reset
    echo "Your input: "
    read input
    case $input in
        1)
            cpu
            ;;
        2)
            gpu
            ;;
        3)
            ram
            ;;

        4)
            misc
            ;;
        5)
            clear
            blue
            animation
            echo "Our github link:"
            space
            animation
            echo "× https://github.com/NotZeetaa/DroidConsole ×"
            space
            animation
            echo "1 - Go back"
            animation
            echo "2 - Exit"
            reset
            space
            animation
            echo "Your input: "
            read input2
            if [ $input2 -eq "1" ]; then
                main
            elif [ $input2 -eq "2" ]; then
                leave
            fi
            reset
            ;;
        6)
            clear
            green
            echo "--------------------------------------------------------------"
            echo "              DroidConsole - Terminal Android Toolbox         "
            echo "--------------------------------------------------------------"
            echo ""
            echo "DroidConsole is a versatile toolbox designed for Android devices,"
            echo "empowering users with a powerful terminal interface for various tasks"
            echo "and commands. From system management to development utilities,"
            echo "DroidConsole provides a seamless experience for users accustomed"
            echo "to working within a command-line environment on their Android devices."
            echo ""
            echo "Project Name: DroidConsole"
            echo "Version: Beta-2"
            echo "License: MIT License"
            echo ""
            echo "--------------------------------------------------------------"
            echo "                              Author                          "
            echo "--------------------------------------------------------------"
            echo ""
            echo "DroidConsole is developed and maintained by NotZeetaa."
            echo "For any inquiries, feedback, or contributions, please contact NotZeetaa (Telegram & GitHub)."
            echo ""
            echo "--------------------------------------------------------------"
            echo "                           License Information               "
            echo "--------------------------------------------------------------"
            echo ""
            echo "DroidConsole is licensed under the MIT License."
            echo "For more information, please refer to the LICENSE file included with the distribution."
            echo ""
            echo "--------------------------------------------------------------"
            echo "                           Disclaimer                        "
            echo "--------------------------------------------------------------"
            echo ""
            echo "This software is provided as-is and without warranty. Use at your own risk."
            space
            animation
            echo "1 - Go back"
            animation
            echo "2 - Exit"
            reset
            space
            animation
            echo "Your input: "
            read input
            if [ $input -eq "1" ]; then
                main
            elif [ $input -eq "2" ]; then
                leave
            fi
            ;;
        7)
            am start -a android.intent.action.VIEW -d "http://notzeetaa.github.io/Donate-NotZeetaa"
            main
            ;;
        8)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

# Call the main function
main
