#!/system/bin/sh

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables

# The only variable that can't be stored on variable cuz it conflict with droid write function
write() {
	echo $2 > $1
}

# Disable restore after executing
resetprop -n droid.restore 0 && sed -i '/droid.restore=/s/.*/droid.restore=0/' $DPROP

