#!/system/bin/sh

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables

cpu_iowait_boost() {
    current_tweak=$(grep 'droid.iowait_boost=' $DPROP | cut -d'=' -f2)
    clear
    red
    animation_title
    echo "********************************"
    animation_title
    echo "      × IO Wait Boost ×      "
    animation_title
    echo "********************************"
    green
    space
    animation
    if [ "$current_tweak" = "1" ]; then
        echo -n "1 - Enable IO Wait Boost "
        current
    else
        echo "1 - Enable IO Wait Boost"
    fi
    animation
    if [ "$current_tweak" = "0" ]; then
        echo -n "2 - Disable IO Wait Boost "
        current
    else
        echo "2 - Disable IO Wait Boost"
    fi
    animation
    echo "3 - Go back"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            resetprop -n droid.iowait_boost 1 && sed -i '/droid.iowait_boost=/s/.*/droid.iowait_boost=1/' $DPROP
            finish
            cpu
            ;;
        2)
            resetprop -n droid.iowait_boost 0 && sed -i '/droid.iowait_boost=/s/.*/droid.iowait_boost=0/' $DPROP
            finish
            cpu
            ;;
        3)
            cpu
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

cpu() {
    current_tweak=$(grep 'droid.cpu_ratelimits=' $DPROP | cut -d'=' -f2)
    clear
    red
    animation_title
    echo "*****************************"
    animation_title
    echo "      × CPU Tweaks ×      "
    animation_title
    echo "*****************************"
    green
    space
    animation
    if [ "$current_tweak" = "1" ]; then
        echo -n "1 - Schedutil rate limits "
        current
    else
        echo "1 - Schedutil rate limits"
    fi
    animation
    echo "2 - Iowait boost"
    animation
    echo "3 - Main"
    animation
    echo "4 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            resetprop -n droid.cpu_ratelimits 1 && sed -i '/droid.cpu_ratelimits=/s/.*/droid.cpu_ratelimits=1/' $DPROP
            finish
            cpu
            ;;
        2)
            cpu_iowait_boost
            ;;
        3)
            main
            ;;
        4)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
    reset
}

# Call the main function
cpu
