#!/system/bin/sh

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables

floating_bar() {
    current_tweak=$(grep 'droid.floating_bar=' $DPROP | cut -d'=' -f2)
    clear
    red
    animation_title
    echo "*******************************"
    animation_title
    echo "      × Floating Search Bar ×      "
    animation_title
    echo "*******************************"
    animation
    space
    echo "This will only work on Pixel launcher (Tested on A14 only)"
    green
    space
    animation
    if [ "$current_tweak" = "1" ]; then
        echo -n "1 - Enable Google Floating Search Bar "
        current
    else
        echo "1 - Enable Google Floating Search Bar"
    fi
    animation
    if [ "$current_tweak" = "0" ]; then
        echo -n "2 - Disable Google Floating Search Bar "
        current
    else
        echo "2 - Disable Google Floating Search Bar"
    fi
    animation
    echo "3 - Go back"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            resetprop -n droid.floating_bar 1 && sed -i '/droid.floating_bar=/s/.*/droid.floating_bar=1/' $DPROP
            finish
            extras
            ;;
        2)
            resetprop -n droid.floating_bar 0 && sed -i '/droid.floating_bar=/s/.*/droid.floating_bar=0/' $DPROP
            finish
            extras
            ;;
        3)
            extras
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

extras() {
    clear
    red
    animation_title
    echo "***********************"
    animation_title
    echo "      × Extras ×      "
    animation_title
    echo "***********************"
    green
    space
    animation
    echo "1 - Google Floating Search Bar"
    animation
    echo "2 - Main"
    animation
    echo "3 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            floating_bar
            ;;
        2)
            main
            ;;
        3)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

# Call the main function
extras