#!/system/bin/sh

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables

gpu_throttling() {
    clear
    red
    animation_title
    echo "********************************"
    animation_title
    echo "      × GPU Throttling ×      "
    animation_title
    echo "********************************"
    green
    space
    animation
    echo "1 - Turn off throttling"
    red
    space
    animation
    echo "* NOTE * Turning off gpu throttling can lead to heat and maybe more dangeours situations * NOTE *"
    green
    space
    animation
    echo "2 - Turn on throttling"
    animation
    echo "3 - Go back"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            resetprop -n droid.gpu_throttling 0 && sed -i '/droid.gpu_throttling=/s/.*/droid.gpu_throttling=0/' $DPROP
            finish
            ;;
        2)
            resetprop -n droid.gpu_throttling 1 && sed -i '/droid.gpu_throttling=/s/.*/droid.gpu_throttling=1/' $DPROP
            finish
            ;;
        3)
            gpu
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

gpu_power_level() {
    clear
    red
    animation_title
    echo "********************************"
    animation_title
    echo "      × GPU power level ×      "
    animation_title
    echo "********************************"
    green
    space
    animation
    echo "1 - Set max GPU power level"
    animation
    echo "2 - Set min GPU power level"
    animation
    echo "3 - Go back"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            resetprop -n droid.gpu_power_lvl 1 && sed -i '/droid.gpu_power_lvl=/s/.*/droid.gpu_power_lvl=1/' $DPROP
            finish
            ;;
        2)
            resetprop -n droid.gpu_power_lvl 0 && sed -i '/droid.gpu_power_lvl=/s/.*/droid.gpu_power_lvl=0/' $DPROP
            finish
            ;;
        3)
            gpu
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

gpu_power_management() {
    clear
    red
    animation_title
    echo "*************************************************"
    animation_title
    echo "      × GPU Power Management Optimization ×      "
    animation_title
    echo "*************************************************"
    green
    space
    animation
    echo "1 - Optimize for performance (This may increase power usage)"
    animation
    echo "2 - Optimize for battery"
    animation
    echo "3 - Go back"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            resetprop -n droid.gpu_power_management 1 && sed -i '/droid.gpu_power_management=/s/.*/droid.gpu_power_management=1/' $DPROP
            finish
            ;;
        2)
            resetprop -n droid.gpu_power_management 0 && sed -i '/droid.gpu_power_management=/s/.*/droid.gpu_power_management=0/' $DPROP
            finish
            ;;
        3)
            gpu
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

gpu() {
    clear
    red
    animation_title
    echo "*****************************"
    animation_title
    echo "      × GPU Tweaks ×      "
    animation_title
    echo "*****************************"
    green
    space
    animation
    echo "1 - GPU Throttling"
    animation
    echo "2 - GPU power level"
    animation
    echo "3 - GPU power management optimization"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            gpu_throttling
            ;;
        2)
            gpu_power_level
            ;;
        3)
            gpu_power_management
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

# Call the main function
gpu
