#!/system/bin/sh

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables

gpu_throttling() {
    clear
    red
    animation_title
    echo "********************************"
    animation_title
    echo "      × GPU Throttling ×      "
    animation_title
    echo "********************************"
    green
    space
    animation
    echo "1 - Turn off throttling"
    red
    space
    animation
    echo "* NOTE * Turning off gpu throttling can lead to heat and maybe more dangeours situations * NOTE *"
    green
    space
    animation
    echo "2 - Turn on throttling"
    animation
    echo "3 - Go back"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    read gpu_throttling_input
    case $gpu_throttling_input in
        1)
            echo "0" > $KGSL/throttling
            sed -i '/^GPU_THROTTLING=/c\GPU_THROTTLING="0"' $CONFIG
            finish
            ;;
        2)
            echo "1" > $KGSL/throttling
            sed -i '/^GPU_THROTTLING=/c\GPU_THROTTLING="1"' $CONFIG
            finish
            ;;
        3)
            gpu
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

gpu_power_level() {
    clear
    red
    animation_title
    echo "********************************"
    animation_title
    echo "      × GPU power level ×      "
    animation_title
    echo "********************************"
    green
    space
    animation
    echo "1 - Set max GPU power level"
    animation
    echo "2 - Set min GPU power level"
    animation
    echo "3 - Go back"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    read gpu_power_level_input
    case $gpu_power_level_input in
        1)
            echo "0" > $KGSL/default_pwrlevel
            sed -i '/^GPU_POWER_LEVEL=/c\GPU_POWER_LEVEL="1"' $CONFIG
            finish
            ;;
        2)
            echo "$MIN_GPU_POWER_LEVEL" > $KGSL/default_pwrlevel
            sed -i '/^GPU_POWER_LEVEL=/c\GPU_POWER_LEVEL="0"' $CONFIG
            finish
            ;;
        3)
            gpu
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

gpu() {
    clear
    red
    animation_title
    echo "*****************************"
    animation_title
    echo "      × GPU Tweaks ×      "
    animation_title
    echo "*****************************"
    green
    space
    animation
    echo "1 - GPU Throttling"
    animation
    echo "2 - GPU power level"
    animation
    echo "3 - Main"
    animation
    echo "4 - Exit"
    reset
    space
    echo "Your input: "
    read gpu_input
    case $gpu_input in
        1)
            gpu_throttling
            ;;
        2)
            gpu_power_level
            ;;
        3)
            main
            ;;
        4)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

# Call the main function
gpu
