#!/system/bin/sh

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables

latency() {
    clear
    red
    animation_title
    echo "*****************************"
    animation_title
    echo "      × Latency Tweaks ×      "
    animation_title
    echo "*****************************"
    space
    echo "WORK IN PROGRESS..."
    green
    space
    animation
    echo "1 - Main"
    animation
    echo "2 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            main
            ;;
        2)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

# Call the main function
latency