#!/system/bin/sh

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables

window_feature() {
    clear
    red
    animation_title
    echo "**********************************"
    animation_title
    echo "      × Window ignore secure ×      "
    animation_title
    echo "**********************************"
    green
    space
    animation
    echo "1 - Enable window ignore secure feature"
    animation
    echo "2 - Disable window ignore secure feature"
    animation
    echo "3 - Go back"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            if grep -q "window_ignore_secure" $WINDOW; then
                settings put secure window_ignore_secure "1"
            fi
            ;;
        2)
            if grep -q "window_ignore_secure" $WINDOW; then
                settings put secure window_ignore_secure "0"
            fi
            ;;
        3)
            misc
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

power_efficient() {
    clear
    red
    animation_title
    echo "********************************"
    animation_title
    echo "      × Power Efficient ×      "
    animation_title
    echo "********************************"
    green
    space
    animation
    echo "1 - Enable Power Efficient"
    animation
    echo "2 - Disable Power Efficient"
    animation
    echo "3 - Go back"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    chmod 7777 $PWR
    read input
    case $input in
        1)
            echo "1" > $PWR
            sed -i '/^POWER_EFFICIENT=/c\POWER_EFFICIENT="1"' $CONFIG
            finish
            misc
            ;;
        2)
            echo "0" > $PWR
            sed -i '/^POWER_EFFICIENT=/c\POWER_EFFICIENT="0"' $CONFIG
            finish
            misc
            ;;
        3)
            misc
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

sultan_optimizations() {
    if [ -d $LYB_TASK ]; then
        clear
        red
        animation_title
        echo "********************************"
        animation_title
        echo "      × Sultan Optimizations ×      "
        animation_title
        echo "********************************"
        green
        space
        animation
        echo "1 - Enable Sultan Optimizations"
        red
        space
        animation
        echo "* NOTE * Might cause bans on games like PUBG and CODM and the system might be unstable * NOTE *"
        space
        green
        echo "* NOTE * This tweak is recommended for Genshin Impact * NOTE *"
        space
        animation
        echo "2 - Disable Sultan Optimizations"
        animation
        echo "3 - Go back"
        animation
        echo "4 - Main"
        animation
        echo "5 - Exit"
        reset
        space
        echo "Your input: "
        read input
        case $input in
            1)
                echo "Y" > $LYB_TASK/parameters/lyb_sultan_pid
                echo "Y" > $LYB_TASK/parameters/lyb_sultan_pid_shrink
                sed -i '/^SULTAN_OPTIMIZATIONS=/c\SULTAN_OPTIMIZATIONS="1"' $CONFIG
                finish
                misc
                ;;
            2)
                echo "N" > $LYB_TASK/parameters/lyb_sultan_pid
                echo "N" > $LYB_TASK/parameters/lyb_sultan_pid_shrink
                sed -i '/^SULTAN_OPTIMIZATIONS=/c\SULTAN_OPTIMIZATIONS="0"' $CONFIG
                finish
                misc
                ;;
            3)
                misc
                ;;
            4)
                main
                ;;
            5)
                leave
                ;;
            *)
                red
                echo "Invalid input!"
                reset
                ;;
        esac
    else
        not_supported
    fi
}

misc() {
    clear
    red
    animation_title
    echo "*****************************"
    animation_title
    echo "      × Miscellaneous ×      "
    animation_title
    echo "*****************************"
    green
    space
    animation
    echo "1 - Window ignore secure feature"
    animation
    echo "2 - Power Efficient"
    animation
    echo "3 - Sultan Optimizations"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            window_feature
            ;;
        2)
            power_efficient
            ;;
        3)
            sultan_optimizations
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

# Call the main function
misc
