#!/system/bin/sh

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables

window_feature() {
    clear
    red
    animation_title
    echo "**********************************"
    animation_title
    echo "      × Window ignore secure ×      "
    animation_title
    echo "**********************************"
    green
    space
    animation
    echo "1 - Enable window ignore secure feature"
    animation
    echo "2 - Disable window ignore secure feature"
    animation
    echo "3 - Go back"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            if grep -q "window_ignore_secure" $WINDOW; then
                settings put secure window_ignore_secure "1"
            fi
            ;;
        2)
            if grep -q "window_ignore_secure" $WINDOW; then
                settings put secure window_ignore_secure "0"
            fi
            ;;
        3)
            misc
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

power_efficient() {
    clear
    red
    animation_title
    echo "********************************"
    animation_title
    echo "      × Power Efficient ×      "
    animation_title
    echo "********************************"
    green
    space
    animation
    echo "1 - Enable Power Efficient"
    animation
    echo "2 - Disable Power Efficient"
    animation
    echo "3 - Go back"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    chmod 7777 $PWR
    read input
    case $input in
        1)
            resetprop -n droid.power_efficient 1 && sed -i '/droid.power_efficient=/s/.*/droid.power_efficient=1/' $DPROP
            finish
            misc
            ;;
        2)
            resetprop -n droid.power_efficient 0 && sed -i '/droid.power_efficient=/s/.*/droid.power_efficient=0/' $DPROP
            finish
            misc
            ;;
        3)
            misc
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

sultan_optimizations() {
    if [ -d $LYB_TASK ]; then
        clear
        red
        animation_title
        echo "********************************"
        animation_title
        echo "      × Sultan Optimizations ×      "
        animation_title
        echo "********************************"
        green
        space
        animation
        echo "1 - Enable Sultan Optimizations"
        red
        space
        animation
        echo "* NOTE * Might cause bans on games like PUBG and CODM and the system might be unstable * NOTE *"
        space
        green
        echo "* NOTE * This tweak is recommended for Genshin Impact * NOTE *"
        space
        animation
        echo "2 - Disable Sultan Optimizations"
        animation
        echo "3 - Go back"
        animation
        echo "4 - Main"
        animation
        echo "5 - Exit"
        reset
        space
        echo "Your input: "
        read input
        case $input in
            1)
                resetprop -n droid.sultan_optimizations 1 && sed -i '/droid.sultan_optimizations=/s/.*/droid.sultan_optimizations=1/' $DPROP
                finish
                misc
                ;;
            2)
                resetprop -n droid.sultan_optimizations 0 && sed -i '/droid.sultan_optimizations=/s/.*/droid.sultan_optimizations=0/' $DPROP
                finish
                misc
                ;;
            3)
                misc
                ;;
            4)
                main
                ;;
            5)
                leave
                ;;
            *)
                red
                echo "Invalid input!"
                reset
                ;;
        esac
    else
        not_supported
    fi
}

battery_health() {
    clear
    red
    animation_title
    echo "*****************************"
    animation_title
    echo "      × Battery Health ×      "
    animation_title
    echo "*****************************"
    reset
    space
    animation
    echo "Battery health: $BATTERY_HEALTH%"
    green
    space
    animation
    echo "1 - Go back"
    animation
    echo "2 - Main"
    animation
    echo "3 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            misc
            ;;
        2)
            main
            ;;
        3)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

dexopt_optimization() {
    clear
    red
    animation_title
    echo "***********************************"
    animation_title
    echo "      × Dexopt Optimization ×      "
    animation_title
    echo "***********************************"
    reset
    space
    animation
    echo "This might take some minutes depending on your phone and apps installed on your system"
    green
    space
    animation
    echo "1 - Optimize"
    animation
    echo "2 - Go back"
    animation
    echo "3 - Main"
    animation
    echo "4 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            dexopt_lvl
            ;;
        2)
            misc
            ;;
        3)
            main
            ;;
        4)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

dexopt_lvl() {
    clear
    red
    animation_title
    echo "***********************************"
    animation_title
    echo "      × Select Optimization Level ×      "
    animation_title
    echo "***********************************"
    reset
    space
    animation
    echo "This will take time dont close this app"
    green
    space
    animation
    echo "1 - Extreme"
    animation
    echo "2 - Speed"
    animation
    echo "3 - Go back"
    animation
    echo "4 - Main"
    animation
    echo "5 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            clear
            yellow
            su -c 'pm compile -m everything -a -p PRIORITY_BOOT' | while IFS= read -r app; do
            echo -ne "\rOptimizing: $app"
            done
            finish
            ;;
        2)
            clear
            yellow
            su -c 'pm compile -m speed -a -p PRIORITY_BOOT' | while IFS= read -r app; do
            echo -ne "\rOptimizing: $app"
            done
            finish
            ;;
        3)
            dexopt_optimization
            ;;
        4)
            main
            ;;
        5)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

fix_rom_glitches() {
    clear
    red
    animation_title
    echo "*****************************"
    animation_title
    echo "      × Fix ROM Glitches ×      "
    animation_title
    echo "*****************************"
    reset
    space
    animation
    echo "This is only needed when u dirty flash your ROM and you see some string text out of context"
    green
    space
    animation
    echo "1 - Fix ROM Glitches"
    animation
    echo "2 - Go back"
    animation
    echo "3 - Main"
    animation
    echo "4 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            su -c 'rm -rf /data/system/package_cache/'
            finish
            ;;
        2)
            misc
            ;;
        3)
            main
            ;;
        4)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

misc() {
    clear
    red
    animation_title
    echo "*****************************"
    animation_title
    echo "      × Miscellaneous ×      "
    animation_title
    echo "*****************************"
    green
    space
    animation
    echo "1 - Window ignore secure feature"
    animation
    echo "2 - Power Efficient"
    animation
    echo "3 - Sultan Optimizations"
    animation
    echo "4 - Check Battery Health"
    animation
    echo "5 - Dexopt Optimization"
    animation
    echo "6 - Fix ROM Glitches"
    animation
    echo "7 - Main"
    animation
    echo "8 - Exit"
    reset
    space
    echo "Your input: "
    read input
    case $input in
        1)
            window_feature
            ;;
        2)
            power_efficient
            ;;
        3)
            sultan_optimizations
            ;;
        4)
            battery_health
            ;;
        5)
            dexopt_optimization
            ;;
        6)
            fix_rom_glitches
            ;;
        7)
            main
            ;;
        8)
            leave
            ;;
        *)
            red
            echo "Invalid input!"
            reset
            ;;
    esac
}

# Call the main function
misc
