#!/system/bin/sh

# Call variables script
. /data/adb/modules/DroidConsole/system/bin/variables

ram() {
    clear
    red
    echo "*****************************"
    echo "      × RAM Tweaks ×      "
    echo "*****************************"
    reset
}

# Call the main function
ram
