#!/system/bin/sh

# Variables
CONFIG=/data/adb/modules/DroidConsole/config.sh
S2=/sys/devices/system/cpu/cpufreq/schedutil
SC=/sys/devices/system/cpu/cpu0/cpufreq/schedutil
KGSL=/sys/class/kgsl/kgsl-3d0/
WINDOW=/data/system/users/0/settings_secure.xml
SWP=/proc/sys/vm/swappiness
PWR=/sys/module/workqueue/parameters/power_efficient
MIN_GPU_POWER_LEVEL=$(cat /sys/class/kgsl/kgsl-3d0/min_pwrlevel)

red() {
    echo -en "\e[31m"
}

green() {
    echo -en "\e[32m"
}

yellow() {
    echo -en "\e[33m"
}

blue() {
    echo -en "\e[34m"
}

pink() {
    echo -en "\e[35m"
}

reset() {
    echo -en "\e[0m"
}

space() {
    echo ""
}

animation_title() {
    sleep 0.2
}

animation() {
    sleep 0.1
}

main() {
    DroidConsole
}

finish() {
    clear
    pink
    echo "Applying it..."
    sleep 1.5
    clear
    yellow
    animation
    echo "**********************"
    animation
    echo "      × Done ×      "
    animation
    echo "**********************"
    space
    blue
    echo "Redirecting..."
    sleep 1
    main
}

leave() {
    clear
    pink
    space
    animation
    echo "**************************************************"
    animation
    echo "      × Thank you for using DroidConsole! ×      "
    animation
    echo "**************************************************"
    space
    reset
    exit 0
}

not_supported() {
    clear
    red
    animation
    echo "**************************************************"
    animation
    echo "      × Your kernel/phone doesn't support this feature! ×      "
    animation
    echo "**************************************************"
    space
    animation
    echo "1 - Go back"
    animation
    echo "2 - Exit"
    reset
    space
    animation
    echo "Your input: "
    read input
    if [ $input -eq "1" ]; then
        main
    elif [ $input -eq "2" ]; then
        leave
    fi
}