#!/system/bin/sh

# Variables
VERSION=BETA-4
CONFIG=/data/adb/modules/DroidConsole/system/bin/config
RESTORE_CONFIG=/data/adb/modules/DroidConsole/system/bin/restore
DPROP=/data/adb/modules/DroidConsole/system.prop
S2=/sys/devices/system/cpu/cpufreq/schedutil
SC=/sys/devices/system/cpu/cpu0/cpufreq/schedutil
KGSL=/sys/class/kgsl/kgsl-3d0/
WINDOW=/data/system/users/0/settings_secure.xml
SWP=/proc/sys/vm/swappiness
PWR=/sys/module/workqueue/parameters/power_efficient
MIN_GPU_POWER_LEVEL=$(cat /sys/class/kgsl/kgsl-3d0/min_pwrlevel)
LYB_TASK=/sys/module/lyb_taskmmu/
CHARGE_FULL=$(cat /sys/class/power_supply/battery/charge_full)
CHARGE_FULL_DESIGN=$(cat /sys/class/power_supply/battery/charge_full_design)
DIFFERENCE=$(( $CHARGE_FULL_DESIGN - $CHARGE_FULL ))
CAPACITY=$(( $CHARGE_FULL / 1000 ))
CAPACITY_DESIGN=$(( $CHARGE_FULL_DESIGN / 1000 ))
BATTERY_HEALTH=$(( 100 * $CAPACITY / $CAPACITY_DESIGN ))
spin[0]="-"
spin[1]="\\"
spin[2]="|"
spin[3]="/"
spin[4]="*"
spin[5]="#"
spin[6]="!"
spin[7]="/"

red() {
    echo -en "\e[31m"
}

green() {
    echo -en "\e[32m"
}

yellow() {
    echo -en "\e[33m"
}

blue() {
    echo -en "\e[34m"
}

pink() {
    echo -en "\e[35m"
}

reset() {
    echo -en "\e[0m"
}

space() {
    echo ""
}

animation_title() {
    sleep 0.1
}

animation() {
    sleep 0.05
}

main() {
    DroidConsole
}

current() {
    yellow
    echo "(Selected)"
    green
}

droid() {
	# Make sure node exist and we have rw access
	if [ -e $1 -a -w $1 ]; then
	# Backup current node value only if its not backed up yet
	if ! grep -qo $1 $RESTORE_CONFIG; then
	B=`cat $1`
	echo write $1 $B >> $RESTORE_CONFIG
	fi
	# Finally write new value
	echo $2 > $1
	fi
}

finish() {
    clear
    pink
    config
    echo -ne "Applying it... ${spin[0]}"
    for i in "${spin[@]}"
    do
    echo -ne "\b$i"
    sleep 0.18
    done
    clear
    yellow
    animation
    echo "**********************"
    animation
    echo "      × Done ×      "
    animation
    echo "**********************"
    space
    blue
    echo -ne "Redirecting... ${spin[0]}"
    for i in "${spin[@]}"
    do
    echo -ne "\b$i"
    sleep 0.18
    done
    main
}

leave() {
    clear
    pink
    space
    animation
    echo "**************************************************"
    animation
    echo "      × Thank you for using DroidConsole! ×      "
    animation
    echo "**************************************************"
    space
    reset
    exit 0
}

not_supported() {
    clear
    red
    animation
    echo "**************************************************"
    animation
    echo "      × Your kernel/phone doesn't support this feature! ×      "
    animation
    echo "**************************************************"
    space
    animation
    echo "1 - Go back"
    animation
    echo "2 - Exit"
    reset
    space
    animation
    echo "Your input: "
    read input
    if [ $input -eq "1" ]; then
        main
    elif [ $input -eq "2" ]; then
        leave
    fi
}
